KAFKA-142 Remove maprfs and hadoop jars from mapr-kafka-connect-hdfs package
Remove hadoop exclusion due to NoClassDefFoundError issue.

(cherry picked from commit bf609af)